# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170529_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_post',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', null=True, upload_to='image/posts/%Y/%m/%d/', verbose_name='Заглавная картинка'),
        ),
    ]
