# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-18 18:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170529_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='Место для текста', verbose_name='Текст'),
        ),
    ]
