# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170529_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_post',
        ),
        migrations.AddField(
            model_name='post',
            name='image_small',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='150x150px', null=True, upload_to='image/posts/%Y/%m/%d/thumbnail/', verbose_name=' Картинка на категорию'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/posts/%Y/%m/%d/', verbose_name='Заглавная картинка'),
        ),
    ]
