# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО Сотрудника')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/worker/%Y/%m/%d/', verbose_name='Фото сотрудника')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Номер телефона')),
                ('department', models.CharField(choices=[('бухгалтерия', 'Бухгалтерия'), ('отдел механизации', 'Отдел механизации')], max_length=2, verbose_name='Выберите отдел')),
                ('info', models.TextField(verbose_name='Информация')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'worker',
            },
        ),
    ]
