# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.CharField(choices=[('бухгалтерия', 'Бухгалтерия'), ('отдел механизации', 'Отдел механизации')], max_length=50, verbose_name='Выберите отдел'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='info',
            field=models.TextField(blank=True, verbose_name='Информация'),
        ),
    ]
