# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allpages', '0003_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='prise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назнавие')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name_plural': 'Прайслист',
                'verbose_name': 'Прайслист',
                'db_table': 'prise',
            },
        ),
    ]
