# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allpages', '0004_prise'),
    ]

    operations = [
        migrations.CreateModel(
            name='prise_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Назнавие')),
                ('text', models.TextField(blank=True, verbose_name='Описание')),
                ('prise', models.ImageField(upload_to='', verbose_name='Цена')),
                ('size', models.CharField(max_length=200, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name_plural': 'Прайслист',
                'db_table': 'prise',
                'verbose_name': 'Прайслист',
            },
        ),
        migrations.DeleteModel(
            name='prise',
        ),
    ]
