# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allpages', '0006_auto_20170616_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prise_list',
            name='prise',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
