# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allpages', '0002_auto_20170610_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название технического средства')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/machine/%Y/%m/%d/', verbose_name='Фото сотрудника')),
                ('text', models.TextField(blank=True, verbose_name='Описание технического средства')),
            ],
            options={
                'verbose_name': 'Техника',
                'verbose_name_plural': 'Техника',
                'db_table': 'machine',
            },
        ),
    ]
