# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allpages', '0005_auto_20170616_0711'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prise_list',
            table='prise_list',
        ),
    ]
