# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allpages', '0007_auto_20170616_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prise_list',
            name='prise',
        ),
    ]
