# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allpages', '0009_auto_20170616_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='prise',
            name='category',
            field=models.CharField(blank=True, choices=[('продукция', 'Продукция'), ('услуги', 'Услуги')], max_length=200, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='prise',
            name='prise_item',
            field=models.CharField(max_length=20, verbose_name='Цена'),
        ),
    ]
